README.md

Closes #7 
Description in README.md has been added how to configure local development environment and be able to use new Vue Storefront theme.

Prepare local development environment

---

components/organisms/o-personal-details.vue
resource/i18n/en-US.csv

Login link not working on Checkout page

---

webpack.config.js

Fixed webpack config for production build

---

CONTRIBUTING.md

Closes #95 
I've already referenced the `develop` branch in Contribution rules. What do you think about that?

Contribution rules

---

pages/Category.vue

Closes #121 
It fixes filters - previously it was not possible sometimes to uncheck them because wrong event was listened to and it caused race condition.

Filter can't be unchecked sometimes

---

components/atoms/a-back-to-top.vue
components/organisms/o-footer.vue

Closes #120 
It fixes 2 issues:
1) Footer width is now the same as rest of the page content. Also link texts have been adapted to fit inside columns. The last column with social icons has width automatically set basing on its content to properly align with the right side of page content. Also icon margin is added to all these icons except the last one.
2) Arrow icon is now positioned in the center of "Back to top" button. Current solution works for any icon size.

Footer improvements

---

components/atoms/a-product-price.vue

Closes #70
Master is now 1.11.1 so this task can be finished.

Feature: 70 - enable price calculations for 1.11.1

---

components/atoms/a-static.vue
index.js
package.json

This module is pretty heavy and we inject content from magento so it should be safe.

remove sanitize-html

---

webpack.config.js

This will merge sfui components in one bundle
Before:
After:

add @storefront-ui to vendor in webpack

---

webpack.config.js

Check if webpack config is for client and apply changes for it.

check client webpack config

---

local.json

Closes #156 
This fixes image dimensions on Category page. Previously images have to be upscaled so they were blurry. Now it looks much better.

Fix blurry images on Category page

---

components/molecules/m-login.vue
components/molecules/m-register.vue

Closes #162 
This PR fixes registration and login procedures to close modal properly.

Fix empty modal after registration or login

---

components/molecules/m-product-carousel.vue
pages/Category.vue

use router-link instead of a

---

pages/Category.vue

Closes #165
Added changes to sort label on category page.

update sort label

---

components/organisms/o-header.vue

Closes #166
Added same filter as is in default theme for main categories in header.

expand categories filter for menu

---

webpack.config.js

Closes #161
This change allows to split code in more aggressive way. For example all libs that have minimum 50kb size will be in separate file.

split code into more files

---

components/core/blocks/Switcher/LanguageSwitcher.vue

Closes #175 
This PR fixes language switcher to show valid country and language codes.

Fixed language switcher showing undefined values

---

components/core/CookieNotification.vue

Closes #174
This change fixes "See details" link in cookie banner.

Fixed "See details" link in cookie banner

---

local.json

This change sharpens product's images. File size is increased by ~100% (from ~5,5 KB to ~11 KB) per image.
_Before change_
_After change_

Sharpen images

---

webpack.config.js

related: #110
glidejs is sfui dependency and it's used on two pages which resulted in separate chunk (`vendors~vsf-home~vsf-product)`. 
So i've added it to sfui chunk which can reduce TTI and looks cleaner :) 
before:
After:

add glide script to sfui chunk

---

components/organisms/o-confirm-order.vue
components/organisms/o-microcart.vue
components/organisms/o-product-details.vue

add temp images for product

---

components/atoms/a-promo-code.vue
resource/i18n/en-US.csv

Closes #200
This adds possibility to delete coupon code on checkout
https://prnt.sc/r7a28j

#200 Add possibility to delete coupon code

---

pages/Category.vue

Closes #208
This change selects (bold) current menu item in category sidebar.

Select current menu item in category sidebar

---

components/molecules/m-login.vue
resource/i18n/en-US.csv

No related issue
These changes delete unnecessary question mark
No sreenshots

Delete question mark

---

layouts/Default.vue

These changes resolve bug with close cart button on iOS
No screenshots

iOS quick fix to cart close button

---

components/organisms/o-notification.vue

Related #196 
This fixes some not supported notification types.
None.

Fixed unknown notification types

---

components/molecules/m-product-additional-info.vue

Related #189 
This PR aligns text and rating stars on moble view.
Before:
After:

Align review stars on mobile view

---

components/atoms/a-product-rating.vue
components/molecules/m-product-additional-info.vue
components/molecules/m-product-short-info.vue
store/ui/index.ts

Closes #229 
After these changes, when user click in reviews info, that opens the revies tab.
No screenshots

#229 Open reviews tab on reviews click

---

pages/Product.vue

Closes #228
After these changes, tabs will be properly reset when user go from one PDP to another PDP
No screenshots

#228 Reset tabs on PDP

---

components/atoms/a-promo-code.vue
components/molecules/m-login.vue
components/molecules/m-register.vue
components/molecules/m-reset-password.vue
components/molecules/m-update-personal-data.vue

Closes #217 
This PR fixes the following console errors:
- on Checkout when sometimes `platformTotals` is not yet available
- on Login, Register and Reset Password, where callback methods does not see `this.$t`
- on Personal Data where `store.state.user.current` may not be available yet in `beforeMount` hook

Fix console errors

---

components/organisms/o-microcart.vue

Closes #210 
These changes add more information about totals in cart
https://prnt.sc/rea4bh

#210 Display all total segments

---

components/organisms/o-microcart.vue
components/organisms/o-order-summary.vue
layouts/Default.vue

Closes #223 
Bundle options (if available) are now displayed in cart and in checkout.

Bundle options are not displayed in cart and checkout

---

components/atoms/a-add-to-cart.vue
components/molecules/m-product-call-to-action.vue

Closes #216 
These changes add the possibility to set in the exact quantity of products adding to the cart.
No screenshots

#216 Add to cart with quantity

---

components/molecules/m-product-additional-info.vue

No related reviews
There is not possible to display "Leave a review" modal. These changes fix it.
No screenshots

Leave a review modal fix

---

components/organisms/o-my-account-order-details.vue

Closes #80
This is a small fix to #80
No screenshots

#80 Order details fix

---

pages/Checkout.vue

Closes #211
Fix for margin on checkout
https://prnt.sc/rl7cn2

#211 Margin on checkout

---

pages/Category.vue

Closes #227 
These changes add hover effect to "Clear all" button in filters sidebar
No screenshots

#227 Add hover effect

---

components/molecules/m-loader.vue

Fix for global loader
No screenshots

Loader fix

---

components/organisms/o-header.vue

Closes #283
These changes fix the problem with jumping horizontal scrollbar during page loading.
No screenshots

#283 Horizontal scrollbar jumps fix

---

components/molecules/m-product-carousel.vue
pages/Home.vue

Closes #224 
This PR slows down a little bit slider animation.

Slider (carousel) animations are too fast

---

package.json

Deletion of 'body-scroll-lock' package from `packages.json`. It is not needed anymore.
No screenshots

Delete body scroll lock package

---

components/organisms/o-footer.vue

Closes #291
These changes hide language switcher when multistore is disabled
No screenshots

#291 Disable language modal

---

package.json

Related #104 
This PR reduces `app` chunk by 12 KB - better this than nothing   😅 
The `sideEffects` option enables some additional optimizations in webpack, but because CSS introduces "side effects" in final page render, all files that may contain styles have to be excluded explicitly - see https://github.com/vuejs/vue-loader/issues/1435 for more details.

Use `sideEffects` webpack optimization

---

components/molecules/m-login.vue
components/molecules/m-register.vue
components/molecules/m-reset-password.vue
components/molecules/modals/m-modal-feature-not-implemented.vue
components/molecules/modals/m-modal-language-switcher.vue
components/molecules/modals/m-modal-newsletter.vue
components/molecules/modals/m-modal-order-confirmation.vue
components/molecules/modals/m-modal-review.vue
components/molecules/modals/m-modal-size-guide.vue
components/molecules/modals/m-modal-terms-and-conditions.vue
components/organisms/o-order-confirmation.vue
layouts/Default.vue
pages/Home.vue
resource/i18n/en-US.csv

Related #303 
This PR fixes layout for modals because it has been corrupted after integrating Storefront UI v0.7.x.

Adapting modals to Storefront UI v0.7.x

---

App.vue
components/organisms/o-bottom-navigation.vue
components/organisms/o-footer.vue
components/organisms/o-header.vue
components/organisms/o-search-panel.vue
components/organisms/o-search.vue

Related #303 
This PR improves search component which has been corrupted after integrating Storefront UI v0.7.x.

Adapt search to Storefront UI v0.7.x

---

components/atoms/a-microcart-icon.vue
components/organisms/o-microcart-panel.vue
components/organisms/o-microcart.vue
layouts/Default.vue

Related #303 
This PR adapts cart component to match current Storefront UI designs.

Adapt cart to Storefront UI v0.7.x

---

components/molecules/m-update-password.vue
components/molecules/m-update-personal-data.vue
components/molecules/modals/m-modal-feature-not-implemented.vue
components/organisms/o-confirm-order.vue
components/organisms/o-my-account-order-details.vue
components/organisms/o-my-account-orders-history.vue
components/organisms/o-my-account-placeholder.vue
components/organisms/o-my-account-shipping-details.vue
pages/MyAccount.vue

Related #303 
This PR improves My Account page after integrating Storefront UI v0.7.x.

Adapt My Account to Storefront UI v0.7.x

---

components/atoms/a-static.vue
pages/Static.vue

Related #303 
This PR improves static pages after updating Storefront UI to v0.7.x.

Adapt static pages to Storefront UI v0.7.x

---

components/organisms/o-confirm-order.vue
components/organisms/o-payment.vue
components/organisms/o-shipping.vue

Closes #336
This PR scrolls up the view for all steps in checkout to simplify the whole checkout procedure that contains a lot of fields.

Focus on the specific step of the checkout

---

components/organisms/o-order-confirmation.vue
resource/i18n/en-US.csv

Closes #332 
This PR shows confirmation after registering for Push notification: **You will receive Push notification about the order.** and fixes the whole Push notifications feature, becasue it didn't trigger view updates.

Inform about registering for Push Notification

---

components/atoms/a-promo-code.vue
components/molecules/m-price-summary.vue
components/organisms/o-confirm-order.vue
components/organisms/o-order-summary.vue
components/organisms/o-personal-details.vue

Closes #331
This PR fixes buttons in checkout.

Fixed layout for buttons in checkout

---

components/organisms/o-personal-details.vue
package.json

Update SFUI to the latest version + one small CSS fix
No screenshots

Update SFUI to 0.7.4

---

package.json

Update version in pacakge.json
No screenshots

Update version in package.json to v1.0-rc.1

---

components/atoms/a-product-rating.vue
components/molecules/m-product-additional-info.vue
components/molecules/m-product-short-info.vue

Closes #330
This change restores a "Leave me review" link in product's review tab. User is also scrolled down to this element.
---

No option to add a new review

---

package.json

Closes #351 
This change fixes problem that prevents from installing dependencies. The package version was not valid.

Can't install dependencies - yarn error

---

components/atoms/a-microcart-icon.vue
components/molecules/m-review-list.vue
components/organisms/o-header.vue
components/organisms/o-notification.vue
package.json
pages/Category.vue

Closes #354
This PR fixes SSR mismatch on every page in Capybara theme. It was caused by Storefront UI lib, and in latest release it does not occur anymore.
In this PR also some minor fixes were introduced after some breaking changes from Storefront UI library.

SSR mismatch in bottom navigation

---

components/organisms/o-footer.vue

Closes #325 
This PR better handles My Account link in footer. It checks if user is logged in and:
- shows login modal if user is not logged in
- navigates to My Account page if user is logged in
No visual change.

Show login modal for my account link in footer

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md

Closes #345
This PR introduces `CHANGELOG.md`.

Add CHANGELOG.md

---

components/atoms/a-account-icon.vue
components/atoms/a-microcart-icon.vue
components/molecules/m-menu.vue
components/molecules/m-product-additional-info.vue
components/molecules/m-product-short-info.vue
components/molecules/m-review-list.vue
components/organisms/o-header.vue
components/organisms/o-search-panel.vue
package.json
pages/Category.vue
pages/MyAccount.vue
pages/Product.vue
pages/Static.vue
store/ui/index.ts

Closes #360
This PR fixes a lot of breaking changes introduced by Storefront UI v0.7.9+:
- header
- mega menu
- search panel
- breadcrumbs
- select not aligned with chevron
Unfortunately, we cannot fully prevent Capybara from similar breaking changes until Storefront UI will start using fixed dependencies of own packages -- as long as there is a `^` in this module https://github.com/DivanteLtd/storefront-ui/blob/6d5385d971eb6d3b3f40bb890407b3e7f9cf62e3/packages/vue/package.json#L33 furher releases in Storefront UI could also break something here in Capybara.

Support Storefront UI v0.7.9+

---

CHANGELOG.md
package.json

No dedicated issue.
This PR updates vesion to `1.0.0-rc.2` and updates Changelog between `rc.1` and `rc.2`.

Version and changelog update for 1.0.0-rc.2

---

CHANGELOG.md
package.json

Bump version to 1.0.1

---

README.md

We should use https link instead of git to allow using it by user without access to repo

use https link instead of git

---

CHANGELOG.md
resource/promoted_offers.json

Corrected the links of home page banners
Closes #379 
After the updated links of Home page banners, user will land on proper pages, instead getting redirect to 404.
Thanks to @gibkigonzo for helping with the correct path for each banner.

Fixed: Home page banner links (#379)

---

CHANGELOG.md
components/molecules/m-login.vue
components/molecules/m-menu.vue
components/molecules/m-product-gallery.vue
components/molecules/m-register.vue
components/molecules/m-related-products.vue
components/molecules/m-reset-password.vue
components/organisms/o-bottom-navigation.vue
components/organisms/o-footer.vue
components/organisms/o-header.vue
components/organisms/o-microcart-panel.vue
components/organisms/o-my-account-order-details.vue
components/organisms/o-newsletter.vue
components/organisms/o-personal-details.vue
components/organisms/o-product-details.vue
components/organisms/o-search.vue
layouts/Default.vue
package.json
pages/Category.vue
pages/Home.vue
pages/Product.vue
store/default-content.ts
store/homepage.ts
store/instagram-images.ts
store/promoted-offers.ts
store/ui/index.ts

Closes #
- use product/findProducts instead of product/list
- use category-next/fetchMenuCategories instead of category/list
- fix problem with changing product color - should be changed product image
- fix close sidebar when push esc button
- add cacheTags to pages
- remove Home page mixin

Apply changes from https://github.com/DivanteLtd/vsf-default/pull/4

---

README.md

Closes #408 
Added the missing step to generate the local.json file.
This will be useful for new user when he/she tries to install vsf-capybara using manual installation steps given.

Updated READ.me file to include missing step in installation.

---

CHANGELOG.md
components/molecules/m-product-add-to-cart.vue
pages/Product.vue

Closes #377 
The `isAddToCartDisabled` computed property has been ported from `vsf-default`.

377: Stock issue

---

components/organisms/o-product-details.vue

Closes #
Fixes the extra margin of add to cart component on product detail page.
**Before:**
**After:**

Fixed extra margin of add to cart component on product details page.

---

components/molecules/m-product-additional-info.vue
resource/i18n/en-US.csv

Added a Sfab for product attributes if they are present.
Closes #386 

Added: attribute tab on product page (#386-Missing-Attributes-tab-product-page)

---

components/molecules/m-related-products.vue
components/organisms/o-my-account-order-details.vue
store/homepage.ts

Closes #417
Replaced deprecated action product/list call with findProducts
NA

Replaced deprecated action product/list call with findProducts

---

CHANGELOG.md
package.json

Closes #462 
Fresh install has Hydration errors, its due to vue version mismatch in capybara theme, I did not get a chance to dig into more why this was failing. It might be due to recent vue release [1] , in this release serialize-javascript dependecy updated from 2.1.2 to 3.1.0
[1] https://github.com/vuejs/vue/releases/tag/v2.6.12
https://github.com/yahoo/serialize-javascript/releases/tag/v3.0.0
https://github.com/yahoo/serialize-javascript/releases/tag/v3.1.0

Fix hydration errors (#462)

---

CHANGELOG.md
pages/Category.vue
resource/i18n/nl-NL.csv

Closes #475
Fixed console warning rleated to Value of key 'Sort by' is not a string

Fixed console warning rleated to Value of key 'Sort by' is not a string #467

---

components/molecules/m-update-personal-data.vue

fix: add pick function to update profile method

---

head.js

4559 remove integrity

---

CHANGELOG.md
components/organisms/o-my-account-shipping-details.vue

Closes #4499
Change userDataToUpdate to properly fetch data from store.

fix: update and delete shipping details

---

CHANGELOG.md
head.js

Preconnect with jsdelivr and googleapis to reduce roundtrip & improve load time.

Preconnect with jsdelivr and googleapis

---

CHANGELOG.md
components/organisms/o-payment.vue
components/organisms/o-shipping.vue
resource/i18n/ar-SY.csv
resource/i18n/cs-CZ.csv
resource/i18n/de-DE.csv
resource/i18n/en-US.csv
resource/i18n/es-ES.csv
resource/i18n/et-EE.csv
resource/i18n/fr-FR.csv
resource/i18n/it-IT.csv
resource/i18n/ja-JP.csv
resource/i18n/nl-NL.csv
resource/i18n/pl-PL.csv
resource/i18n/pt-BR.csv
resource/i18n/ru-RU.csv
resource/i18n/zh-cn.csv

Closes #4767
Add validation to phone number input in shipping and payment components. 

feat: add phone number validation in shipping and payment

---

CHANGELOG.md
helpers/price.ts

Closes #493
Price change when choosing configurable product the second time.

Anat dev branch

---

CHANGELOG.md
components/organisms/o-payment.vue
components/organisms/o-shipping.vue
package.json

Preparation to release 1.0.4

---

CHANGELOG.md
components/molecules/m-product-gallery.vue

#549 
Closes #549 
The changes will help to remove the console error related to undefined on the product page.

Improved: the code to fix the error of undefined on the product page (#549)

---

CHANGELOG.md
index.js
package.json

Closes #
- Added `VueObserveVisibility` and `VueLazyload` dependency

Added VueLazyload and VueObserveVisibility

---

CHANGELOG.md
store/ui/modals.ts

Fix for 1.12.3

---

CHANGELOG.md

Fix versions

---

CHANGELOG.md
components/organisms/o-microcart-panel.vue

Closes #644 
Fix for removing the product from Cart for Desktop devices.

fix: remove product from Cart on Desktop

---

CHANGELOG.md
components/organisms/o-header.vue

Closes #642 
Close Mega Menu after clicking on the menu item 

fix: close mega menu after clicking on the menu item

---

CHANGELOG.md
MIGRATION_GUIDE.md
components/molecules/m-menu.vue

Fix broken menu

---

CHANGELOG.md
components/organisms/o-payment.vue
components/organisms/o-shipping.vue

Set missing require for `phoneNumber` on the Checkout steps (shipping / payment)

fix: missing required for phoneNumber

---

CHANGELOG.md
components/molecules/m-product-gallery.vue
components/organisms/o-header.vue
components/organisms/o-microcart-panel.vue
components/organisms/o-payment.vue
components/organisms/o-shipping.vue
store/ui/modals.ts

Release v1.0.5

---

CHANGELOG.md
components/molecules/m-product-gallery.vue
components/organisms/o-header.vue
components/organisms/o-microcart-panel.vue
components/organisms/o-payment.vue
components/organisms/o-shipping.vue
package.json

Resolved conflict dev 1

---

components/organisms/o-microcart-panel.vue

fix: import missing SfCircleIcon

---

CHANGELOG.md
components/organisms/o-personal-details.vue

#601 
Closes #
Updated o-personal-details to match latest design

Updated o-personal-details to match latest design (#601)

---

CHANGELOG.md
pages/Category.vue

#622 
Closes #622 
Navbar is visible now while scrolling

Made navbar visible while scrolling (#622)

---

CHANGELOG.md
components/organisms/o-microcart-panel.vue

Closes #576 
Height of microcart was not rendering perfectly, removed the logic restraining the height of the microcart.
Before
After

Improved: Height for the micro cart on mobile (#576)

---

CHANGELOG.md
components/organisms/o-payment.vue
components/organisms/o-shipping.vue

#589 
Closes #589 
Updated the error message for the zip code field on the shipping and payment page

Improved: the error message for the zip-code field on shipping and payment page(#589)

---

CHANGELOG.md
components/molecules/m-product-carousel.vue

#623 
Closes #623 
Improved speed of carousel in m-product-carousel
NA

Improved speed of carousel in m-product-carousel (#623)

---

CHANGELOG.md

While merging some old PRs some of the change log got jumbled up. Cleaned that up.
- [x ] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

Cleaned up change log and old PRs

---

CHANGELOG.md
components/organisms/o-header.vue
components/organisms/o-search-panel.vue

#542 
Closes #542 
Improved font side of search text and also no result margin

Improved: Search on mobile (#542)

---

CHANGELOG.md
pages/Category.vue

#669 
#669 
Closes #
Removed backdrop filter to position sort by drop down of category page in mobile

Removed backdrop filter to position sort by drop down of category page in mobile (#669)

---

CHANGELOG.md
resource/promoted_offers.json

#445 
Closes #445 
Updated the banner links of product page as they were not working previously.

Updated: the links of banners in product page(#445)

---

CHANGELOG.md
README.md

#676 
Closes #676 
Added discord link on the place of slack link.
-  [x] I read and followed [contribution rules](https://github.com/DivanteLtd/vsf-capybara/blob/master/CONTRIBUTING.md)

Replaced: the slack community link with discord link(676)

---

CHANGELOG.md
components/organisms/o-my-account-shipping-details.vue

#608 
Closes #608 
Simplifies css styling

Refactored add/update address form styling of o-my-account-shipping-details (#608)

---

CHANGELOG.md
components/molecules/m-update-personal-data.vue

#604 
Closes #604 
Updated m-update-personal-data to match the latest design

Updated m-update-personal-data to match the latest design (#604)

---

CHANGELOG.md
pages/Category.vue

#617 
Closes #617 
Refactored styling of category page

Refactored styling of category page (#617)

---

CHANGELOG.md
components/atoms/a-product-rating.vue
components/molecules/m-product-add-to-cart.vue
components/molecules/m-product-additional-info.vue
components/molecules/m-product-gallery.vue
components/molecules/m-product-options-configurable.vue
components/molecules/m-product-short-info.vue
components/organisms/o-product-details.vue
pages/Product.vue

#621 
Closes #621 
Simplified styling of product page

Refactored styling of product page (#621)

---

App.vue
components/organisms/o-microcart-panel.vue
components/organisms/o-microcart.vue

Closes #
Modal was not working properly so removed overlay z-index property

Removed overlay z-index property, helper for calculating product price in cart and removed body scroll (#v1.0.6)
