- .gitignore
- .huskyrc.js
- .lintstagedrc.js
- package.json
Closes #18 
Husky and lint-staged tools have been integrated and configured similarly like in `vue-storefront` repo. The only difference is that in `vsf-capybara` lint-staged tries to automatically fix problems and then it adds modified files again to git index.
The `test` script has been renamed to `test:unit` to match with `vue-storefront` repo and because in `vsf-capybara` there are not tests yet it returns success code 0 to be able to pass `pre-push` git hook (called by just installed Husky), which calls `yarn test:unit` :wink:
In screenshot below it can be seen that an attempt to commit a change with `console.log()` at line 34 is rejected by Husky which calls ESLint in `production` mode, where `console` and `debugger` commands are not permitted.
> Husky and lint-staged tools integrated and configured

- README.md
- package.json
- webpack.config.js
Closes #10 
There were 2 options how to integrate `storefront-ui` library with `vsf-capybara`:
- using its default (official) releases - easy and not challenging enough approach 😉 
- stick with `develop` branch, which is updated much more often - it is a little bit more complex since `storefront-ui` uses own workspaces and after fetching it directly from GitHub via URL (rather than using package name) it is not ready to be used.
As I heard from `storefront-ui` team it is better from development point of view to choose latter approach and use their lib on `develop` branch. Due to that fact new `sfui` script has been introduced to prepare `storefront-ui` library and to be able to import its components into new theme. Additionally, minor webpack change also has to be introduced to properly …
> storefront-ui@develop branch integrated

- components/core/Logo.vue
- components/core/blocks/Header/AccountIcon.vue
- components/core/blocks/Header/Header.vue
- components/core/blocks/Header/MicrocartIcon.vue
- components/core/blocks/Header/SearchIcon.vue
- components/core/blocks/Header/WishlistIcon.vue
- package.json
Closes #43
In task description there is info `Wish list icon is visible but does not contain any logic.`. I left logic that opens this sidebar, because it is just one method that we will change/replace in future.
1.How about moving new component to some other new folders? We use `/components/core/*` or `components/theme/*`, but this is confusing because there are new and old components. And also I never understood this separation `core` / `theme` because 90% of components are in `core` and you will change components in `core` anyway if you need to. wdyt? If there is some good reason to have such a separation then we can make `core_temp` and `theme_temp` for migration time.
2.Do we want to use anything from `src/themes/capybara/css`? there are some utility css, grid. Maybe we should …
> update Header and related components

- config/modules.ts
- webpack.config.js
Closes #72 
Now it is possible to disable modules in theme: just comment out unused module in `<path to capybara theme>/config/modules.ts`. By default `AmpRendererModule` has been disabled.
> Disable unused modules from vsf

- package.json
- webpack.config.js
Closes #71 
The `SfTable` component in `storefront-ui` uses `calc()` with CSS variable [here](https://github.com/DivanteLtd/storefront-ui/blob/3584689ff3890d748460cededbebc9686e42c538/packages/shared/styles/components/SfTable.scss#L40)
```
flex: 0 0 calc(100% / var(--mobile-column));
```
According to [this note](https://github.com/philipwalton/flexbugs#flexbug-8) 
> `flex-basis` doesn't support `calc()`
so this line is parsed by `postcss-flexbugs-fixes` which tries to re-write it as separate `flex-basis`, `flex-shrink` and `flex-grow` declarations. Unfortunately [this regex](https://github.com/luisrudge/postcss-flexbugs-fixes/blob/c51f4e749722982498bef27c36dbee1ebd1e0a4d/bugs/bug81a.js#L4) does not support CSS variables inside `calc()` in `flex` declaration and due to that this rule is …
> Fix `postcss-flexbugs-fixes` plugin integration with `storefront-ui`

- components/molecules/modals/m-modal-account-benefits.vue
- components/molecules/modals/m-modal-terms-and-conditions.vue
`modalData` prop was missing in two modals, which was the reason that they were not possible to close: `TypeError: "this.modalData is undefined"`
> Fixed missing modalData prop

- components/molecules/m-review-list.vue
- pages/Category.vue
Closes #123 
These changes hide pagination element if there is only one page to show.
> Hide pagination if there is only one page

- pages/Category.vue
Closes #122 
Empty string is used if filter count is 0 so now after opening filter sidebar first time it will not show meaningless zeros anymore.
> Do not show filter count if it is 0

- components/organisms/o-footer.vue
Closes #132
It fixes `src` path for social icons in footer.
Now it works fine on any page:
> Fixed src path for social icons

- webpack.config.js
Closes #138 
After Vue Storefront v1.11.1 it is now possible to simplify `webpack.config.js` because it will never be called with configuration object wrapped inside `default` key for development build 🎉 
No changes.
> Simplify webpack.config.js after VSF v1.11.1

- components/atoms/a-product-price.vue
- components/molecules/m-product-carousel.vue
- components/organisms/o-microcart.vue
- helpers/index.ts
- helpers/price.ts
- pages/Category.vue
Closes #142
This PR unifies and fixes price calculation in all places.
Previous implementation was moved from `components\atoms\a-product-price.vue` to new `helpers\price.ts` and then it is used in all places where it is needed. It had to be moved to a helper module to be able to use it as a function - we are using components like `SfCollectedProduct` or `SfProductCard` which could not use previous `a-product-price.vue`, but they require providing prices (regular and special) as props.
If calculated price is 0 then it is not displayed.
This PR also fixes price calculation in microcart: now it is a sum of all product's prices including taxes - just like it is in default theme.
Now prices are calculated correctly:
> Fix and unify price calculation methods

- webpack.config.js
Move common libs to vendor.js, then app.js will be lighter and will load faster.
> move common libs from app.js to vendor.js

- components/atoms/a-images-grid.vue
- helpers/index.ts
- pages/Home.vue
- store/ui/index.ts
Closes #168 
This fixes duplicated `GET '/'` on Homepage. It was caused because for SSR empty `:image` prop was provided and this empty string was used as `background-image: url('')` in `SfHeroItem` component. Empty image URL in `url('')` is a relative URL, which resolves to the base URL, in this case the same as our Homepage, so it was requested again with headers `Accept: image/webp,*/*` (in Firefox) or `Accept: image/webp,image/apng,image/*,*/*;q=0.8` (in Chrome) saying "we want an image this time".
So it was just needed to provide valid image URL to prevent double `GET '/'` requests.
> Fixed duplicated requests on Homepage in SSR

- components/organisms/o-header.vue
- helpers/index.ts
- pages/Category.vue
Closes #172 
This change unifies categories in header and in the sidebar. Also number of products in given category is not shown if `product_count` is 0 - the same as in _Filters_ sidebar.
> Unify categories shown in header with these on Category page

- package.json
This PR changes Storefront UI version we are using. It is safer not to stick with always "latest" library version, especially if "breaking changes" are announced in advance in 0.6.0.
Version **^0.5.1** means >**=0.5.1** and <**0.6.0**
> Don't use latest Storefront UI version

- components/atoms/a-home-icon.vue
- components/atoms/a-microcart-icon.vue
- components/organisms/o-bottom-navigation.vue
- components/organisms/o-footer.vue
- layouts/Default.vue
Closes #188 
This PR introduces bottom navigation for mobile view and it contains the following links:
- back to home,
- open search sidebar,
- open account modal
- open cart sidebar (as big green floating icon).
The 'back to top' floating icon has been removed temporarily.
> Add bottom navigation on mobile view

- components/atoms/a-product-rating.vue
Closes #189 
This was a very interesting bug to investigate  😅 
It turned out that this bug depends on a random hash fragment in `data-v-[hash]` attributes in our components with scoped styles. These scoped styles are always applied in alphabetical order and this was the reason that sometimes (i.e. in my local development builds) this bug was not present.
I fixed that by increasing CSS specificity to be sure that our styles are always applied in expected order.
In one build (in this case in production on capybara.storefrontcloud.io) this bug exists because parent element `.a-product-rating` has `data-v-54adf582` and child `.a-text-action` has `data-v-f3ca352e`. Scope styles assigned to these attributes are applied in alphabetical order: **first from parent** `data-v-54adf582` and **then …
> Center 'Read all review' link with star ratings

- webpack.config.js
Related #110 
This PR cleans up our bundles: it moves all libs from `node_modules` to `vendor` chunk - except Storefront UI which has own `sfui` chunk as before. The total size of all chunks is decreased by ~10 KB.
Before:
After:
> webpack optimizations - move all node_modules libs to vendor

- components/organisms/o-bottom-navigation.vue
Related #188
This fixes `z-index` for bottom navigation if there is a modal or sidebar opened. Bottom navigation was rendered "above" overlay or sidebar which did not look nice.
Before:
After:
> Fixed z-index for bottom navigation

- pages/Category.vue
No related issue.
This change prevents from crashing if `category-next/getAvailableFilters` is not available.
> Fixed filter sidebar if filters are missing

- webpack.config.js
In this change we split vendor into initial chunk and async chunk. Size of bundle didn't change. Purpose of this change is that we will load on preload libs that are needed and rest in prefetch. So vendor-initial is smaller then previous vendor
before:
After:
Bundle before:
Bundle after:
> create async and initial vendor

- components/molecules/m-login.vue
- components/molecules/m-register.vue
- components/molecules/m-reset-password.vue
Closes #199
This change allows submitting login, register and password reset forms by pressing Enter key.
**Remark**: currently there is a bug in Storefront UI https://github.com/DivanteLtd/storefront-ui/issues/782 which causes that clicking on "Show password" icon in password input triggers `submit` event, because by default buttons without type within forms are assumed to be of type `submit`.
> Handle Enter key in login and register forms

- webpack.config.js
Related #110 
This change simplifies webpack config a little bit and it also enforces to create only one `vsf-search-adapter` file. Previously there were `vsf-search-adapter-0` and `vsf-search-adapter-1`.
After changes:
> webpack cleanup and optimizations

- layouts/Default.vue
- pages/Category.vue
Closes #236
This PR fixes overlapping _Filters_ sidebar by bottom navigation on mobile view. It also fixes bottom buttons in _Filters_ sidebar - they were cut on the bottom.
> Bottom navigation on mobile is shown on top of sidebar

- components/organisms/o-microcart.vue
Closes #238
This PR fixes bottom button in cart sidebar on mobile view - button is no longer cut on the bottom.
> Bottom button in cart sidebar is cut on mobile view

- components/molecules/modals/m-modal-feature-not-implemented.vue
- components/organisms/o-my-account-orders-history.vue
- pages/Home.vue
- store/ui/modals.ts
Closes #220
These changes show notification with information that feature is not implemented when user clicks "Download all" on the orders history page.
No screenshots
> #220 Download all orders

- components/organisms/o-header.vue
- pages/Category.vue
Closes #207 
This PR selects main category in header and sub-category in sidebar in bold. Previously sub-category was marked as selected only if it exactly matched current category. Now it is matched even if current category is deeper in a hierarchy.
> Mark selected category

- components/molecules/m-menu.vue
- components/organisms/o-header.vue
- components/organisms/o-search-panel.vue
- components/organisms/o-search.vue
- layouts/Default.vue
Closes #263 
This PR fixes overlapping mega menu with search results - if search is opened then mega menu links are hidden. Also search results were aligned to mega menu overlay width to be consistent.
Search results on mobile view were also fixed (they were cut on the bottom by `o-bottom-navigation` component).
Dektop view
Mobile view
> Mega menu is shown behind search overlay

- layouts/Default.vue
- package.json
- pages/Category.vue
Closes #115
These changes add `<link rel="prefetch">` with URLs to products on the category page. This will force the browser to prefetch product pages.
I tested adding links to ES queries to prefetch but it won't work. The problem is because ES query to get product data is sent by the server (not browser), so prefetching it by the browser hasn't sense.
https://prnt.sc/rl4ilk
> #115 Smart link prefetching

- components/organisms/o-search-panel.vue
- components/organisms/o-search.vue
Closes #279
This fixes position for `LoadingSpinner` and `LoadingError` for search async component.
> Fix LoadingError and LoadingSpinner position

- components/organisms/o-my-account-order-details.vue
Closes #285 
This PR fixes Order history view when shipping information is not available in current ordered item.
> Order history does not work if shipping info is missing

- config/modules.ts
No related issue
Disabling of GTM module which is not used on our demo. These changes decrease app.js bundle size by a few KB.
No screenshots
> Disable GTM module

- components/organisms/o-confirm-order.vue
This class is used by third-party extensions to detect "Place the order" button. For example, Braintree Payment extension uses it (https://github.com/danrcoull/vsf-payment-braintree)
No screenshots
> Add class to place the order button

- components/organisms/o-my-account-order-details.vue
- local.json
- package.json
Closes #112 
This PR is needed to make Capybara theme compatible with VSF v1.12. It uses the latest improvements added in VSF and they are enabled in `local.json` file.
This PR can be merged when:
- https://github.com/DivanteLtd/vue-storefront/pull/4212 is merged
- there is a VSF API v1.12 instance available and can be used by Capybara test site on https://capybara.storefrontcloud.io/
So after merging this PR please do the following on test site https://capybara.storefrontcloud.io/:
- merge `local.json` from this PR with the one on test site
- add VSF API v1.12 URL to `api.url` configuration in `local.json` on test site.
- update VSF branch to `develop` or v1.12 (if it will be available at that time) on test site.
> Make Capybara compatible with VSF v1.12

- webpack.config.js
Related #104 
This PR extracts GraphQL-related modules to separate chunk to decrease `vendor-async` size.
Results are promising:
- before this change total load size on Homepage was 1502872 B
- after this change total load size on Homepage is 1318239 B
- load size reduction is **~12,3%**  🎉 
The only one disadvantage is that suddenly there are 2 `vsf-search-adapter-0` and `vsf-search-adapter-1` chunks despite the rule in our webpack configuration to always join them together  🤔
This is strange but I think that benefits from this PR are more important.
> Create separate GraphQL chunk

- components/molecules/m-login.vue
- components/molecules/m-register.vue
- components/molecules/m-reset-password.vue
Closes #298 
This change fixes double method invocation on login, register or reset password modals. By default button inside a form triggers `onSubmit` method so if a button has also own `onClick` method the same as `onSubmit`, then this method is called twice.
> Authentication methods are triggered twice

- webpack.config.js
Related #104 
This PR reverts recent webpack change that created separate GraphQL chunk. It worked as expected on v1.11.x but it stopped on v1.12, where the `vsf-graphql` chunk is always fetched on Homepage so this improvement does not make sense anymore. It looks like this is a bigger issue here so it is better to just revert previous PR now and investigate this problem.
> Revert: Separate GraphQL chunk

- App.vue
- components/organisms/o-notification.vue
Related #303 
This PR fixes layout for notifications because it has been corrupted after integrating Storefront UI v0.7.x.
> Adapting notifications to Storefront UI v0.7.x

- components/organisms/o-my-account-order-details.vue
Closes #312 
This PR fixes images in order history that might be to big if image proxy is disabled or not configured.
> Limit max size of image in order history

- components/organisms/o-microcart-panel.vue
Closes #337 
Removes 'more actions' icon in cart in mobile view because it is not used.
> Unnecessary 'more actions' icon in cart in mobile view

- components/organisms/o-microcart-panel.vue
Closes #335 
This fixes 'empty cart' icon, which was not displayed in cart sidebar.
> 'Empty cart' icon is not displayed

- local.json
Related #343
Quicklink causes infinite resource loading. We need to disable it by default until we find good solution.
No screenshots
> Disable quicklink by default

- components/molecules/m-product-options-configurable.vue
- components/molecules/m-product-short-info.vue
- components/organisms/o-product-details.vue
Closes #329 
This PR fixes some runtime errors we had on PDP page, like duplicated keys in `v-for` directive. It also enables color selector on mobile view. Size guide should be now visible in all cases.
---
> Size guide is not visible when user switches to PDP from related list

- pages/Category.vue
Closes #328 
This PR fixes overlapping issue with dropdown list and `SfProductCard` hover styles -- see screenshot below: dropdown list is rendered on top of hovered `SfProductCard`.
Second issue regarding not properly positioned arrow inside drodown list has been fixed in Storefront UI in v0.7.2.
> Problem with displaying dropdown list

- components/molecules/m-product-additional-info.vue
Closes #228 
After opening product page always first tab with description will be shown.
> Tabs on the product page are not reset properly

- components/molecules/m-price-summary.vue
- components/organisms/o-confirm-order.vue
- components/organisms/o-order-summary.vue
Closes #361
This PR adds possibility to add and remove discount coupon on mobile view. This is possible in the last step in the checkout.
> Support discount coupons in mobile view

- CHANGELOG.md
- helpers/price.ts
In 1.12 there will be updated typing for `getBundleOptionsValues` and as ` const selectedBundleOptions = Object.values(get(product, 'product_option.extension_attributes.bundle_options', {}))` returns `uknown[]` it will fail in 1.12. I can't add new type (because it not exist in 1.11), so I've added `any[]`.
> update typing for price helper

- CHANGELOG.md
- package.json
In sfui to version [0.7.11](https://github.com/DivanteLtd/storefront-ui/commit/d699b3a3c56c7fe13a55b970d873e2333b18c358#diff-099a765d0e8e27c90657641e46433003L33) there was a dash in version number and right now we use components in version 0.7.10 and styles in newest version 0.7.17. Which result in some bugs. So with this change we will have both components and styles from sfui in version 0.7.11. It should be better starting point for making update to newest sfui version.
before: 
after:
> update sfui to 0.7.11

- CHANGELOG.md
- components/molecules/m-error.vue
Related Issues
Closes #398 
Error page was of too much height, due to which "Back" and "Returned to Home" were not visible without scrolling.
Found that margin on error image was high, adjusted the margin for .error class from '2xl * 3' to 'xl * 2' .
Before Mobile :
Before Desktop:
After Mobile:
After Desktop:
> Fixed: Error page on mobile and desktop (#398-Adjust-error-page)

- pages/Home.vue
Removed the CSS properties which were forcing some section with class 'section' (Bestseller section and share your look section) on home page, to have padding on mobile view, which cause less space for them to occupy. 
Also these properties were making these section shrink and not in align with other sections of home page.
#382 
Closes #382 
As mentioned in the issue, size of bestseller carousel was smaller in comparison to other carousels.
On debugging, I found that .section class have padding on mobile devices, this class was added on #shareyourlook and #bestseller section, and causing them to shrink more in the mobile devices. 
Due to which size of bestseller carousel was smaller in comparison to other carousels.
Before 
After
**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` …
>  Improved: Size of Products in bestsellers section (#382-bestseller-products-size)

- CHANGELOG.md
- components/atoms/a-sort-icon.vue
- pages/Category.vue
Closes #381
Filters bar on mobile has been updated. Current Storefront UI designs do not provide sorting capabilities for mobile view so I've slightly mixed previous concept with current one 😉 
> 381: Update filters bar on category page

- CHANGELOG.md
- components/molecules/m-product-short-info.vue
Closes #393
In PDP top section `product.short_description` is used (if available), or `product.description`.
> 393: Use short description in PDP top section

- CHANGELOG.md
- components/molecules/m-product-options-configurable.vue
#436 
Closes #436 
Fixed the getAttributeLabel computed property for configurable options.
Before:
After:
> #436 Fixed selected size option on product page.

- CHANGELOG.md
- components/molecules/m-login.vue
Closes #438 
Now I can use i18n dictionaries for translate title in the login modal window
> #438 used i18n for login title.

- pages/Category.vue
Closes #443 
White color is not visible due to white background in color filters.
Added border for that
Before
After 
> Improved: Styling around color selector on filters in category page (#443)

- pages/Product.vue
Closes #442 
If product have white variant in color, it is not visible due to white background.
Added border in color picker
Beofre
After
> Improved: Styling around color filters (#442)

- components/molecules/m-product-carousel.vue
On mobile devices if you swipe the carousals, it takes time to get stationary.
Experience should be smooth while swiping the carousal
Reduced the, animationDuration and rewindDuration to 2000 from 3000
Closes #444 
> Improved: carousel time in product carousel (#444)

- pages/MyAccount.vue
Closes #448 
Logout button was placed after order details and in UI, it seems like its inside order details.
Moved it in between order details and personal details
Before
After
> Improved: Position of logout (#448)

- components/organisms/o-my-account-shipping-details.vue
Closes #441 
Defined '--select-dropdown-position' as relative.
It was not visible as in mobile view this SfSelect is under many layers and default value(fixed) was not able to display it.
Before
After
> Fixed: Dropdown in adding shipping address (#441)

- components/organisms/o-my-account-order-details.vue
Used sku instead of product_id while preparing order line items product
Closes #415
While preparing order item product detail we are using sku to fetch product detail, but at the time of preparing item product detail we are comparing using product_id. 
This may cause issue when we are using different systems,
also to make code consistent it should use sku while comparison as well. 
> Used sku instead of product_id while preparing order line items product detail

- README.md
Fixes path for `generate-local-config.js` to be exact to capybara's submodule path example.
> Fix src path for added submodule in README.md

- CHANGELOG.md
- components/molecules/m-menu.vue
- package.json
Improved the use of flex wrap, justify content and margins to give proper spacing on mobile view.
Closes #465 
Tiles will be visible properly on mobile view.
Before
After
> Fixed: Broken tiles of mega menu  (#465-Mega-Menu-Tiles-Mobile)

- CHANGELOG.md
- components/atoms/a-logo.vue
Removed overridden Height of logo in a-logo
Closes #490 
Height of logo in a-logo is forcefully overridden, SFUI default height works perfectly
Before
After
> Removed: Overridden logo height(#490)

- components/organisms/o-bottom-navigation.vue
Called "ui/closeMenu" in the function for navigating to profile in the bottom navigation.
Closes #526 
Menu should get close on clicking any link on bottom navigation
Before
After
> Fixed: Closing of menu on clicking the profile icon on Mobile(#526)

- CHANGELOG.md
- components/organisms/o-bottom-navigation.vue
Replaced icon from 'account' to 'profile', this made the icon for my account consistent for mobile and desktop view
Closes #553 
Replaced icon from 'account' to 'profile', this made the icon for my account consistent for mobile and desktop view
Before
After
> Improved: Consistency of profile icon (#533)

- pages/Category.vue
#563 
Closes #563 
The changes will check whether the to and from in the $route are same before changing the page, if not then set the currentPage to 1 and change the category, which will help in loading the products.
> Updated: code to change the category from any category page (#563)

- CHANGELOG.md
- components/molecules/m-product-gallery.vue
Closes #643 
Fix for displaying wrong order of product images on PDP after clicked on filtered product from PLP
**BEFORE**
**AFTER**
> fix: wrong product img on PDP after clicked on filtered product from PLP

- CHANGELOG.md
- components/organisms/o-microcart-panel.vue
Closes https://github.com/vuestorefront/vue-storefront/issues/4460
Used new `getProductPrice` instead calculation in the vue component
Related PR: https://github.com/vuestorefront/vue-storefront/pull/5973
> fix: calculation prices after coupon

- App.vue
- CHANGELOG.md
Memory is never released and thus memory usage keeps increasing after each page reload.
In the default VSF theme the template imports are tagged with webpackChunkName and thus dynamically imported, in the Capybara theme however the imports are missing the webpackChunkName comment, which seems to cause the memory leak.
GC reclaims unused memory.
1. Install the latest VSF with the Capybara theme in Docker.
2. Run, configure and import the demo data set
3. Run 'docker stats'
4. Browse to your vsf instance and keep reloading the page.
5. You should see the memory usage of your vsf container increase with each reload.
- [X ] YES
- Browser: Firefox 78.0.2 (64-bits)
- OS: Windows 10 pro 2006
- Code Version: latest Master (1.0.3)
> Memory increases after each page reload. 

- CHANGELOG.md
- components/atoms/a-product-quantity.vue
#614 
Closes #614 
Fixed spacing of a-product-quantity
> Fixed spacing of a-product-quantity(#614)

- App.vue
- CHANGELOG.md
#503 
Closes #503 
There was no minimum height for page which make footer come up in empty state so added min-height to global max height css rule and defined height for footer, header and header mobile.
> Added: Min Height to main contect in the page (#503)

- CHANGELOG.md
- pages/Product.vue
#534 
Closes #534 
Removed that padding for consistent behaviour.
> Removed Horizontal Padding on product bottom section in product page (#534)

- CHANGELOG.md
- components/molecules/modals/m-modal-authentication.vue
#434 
Closes #434 
Removed the mode from the transition and used the transition classes.
After:
https://user-images.githubusercontent.com/41404838/105496242-39ae7c00-5ce3-11eb-8289-d406cf812241.mov
> Updated: code to make the tab index work on the authentication modals(#434)

- CHANGELOG.md
- components/organisms/o-my-account-shipping-details.vue
#610 
Closes #610 
Refactored shipping details styling
> Refactored shipping details styling of o-my-account-shipping -details (#610)

- CHANGELOG.md
- components/molecules/m-update-password.vue
#606 
Closes #606 
Refactored styling of m-update-password
> Refactored m-update-password styling (#606)

- CHANGELOG.md
- components/organisms/o-search-panel.vue
#613 
Closes #613 
Fixed the position of categories during scrolling in o-search-panel
> Fixed the position of categories during scrolling in o-search-panel (#613)
